name: CI/CD Pipeline for FastAPI Application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Authenticate with Google Cloud
        uses: google-github-actions/setup-gcloud@v0.3.0  # Ensure this uses the latest verified version
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: prod-414022  # Simplified for consistency
          export_default_credentials: true

      - name: Configure gcloud CLI
        run: gcloud config set project prod-414022
        
      # This step is commented out; uncomment if creating a new App Engine app
      # - name: Create App Engine Application
      #   run: gcloud app create --project=${{ env.GCLOUD_PROJECT }} --region=us-central
      #   env:
      #     GCLOUD_PROJECT: prod-414022
  
      - name: Deploy to Google App Engine
        run: gcloud app deploy app.yaml --quiet
        working-directory: ./app

      - name: Run Alembic migrations
        run: alembic upgrade head
        env:
          DATABASE_URL: ${{ secrets.PRODUCTION_DATABASE_URL }}

